---
aliases: [curse-of-knowledge]
title: "Fellow R Instructors: Beware of the Curse of Knowledge!"
authors: [arie]
# summary: Avoid the curse of knowledge when teaching R
date: '2020-02-14'
categories:
  - education
tags:
  - teaching
  - R
  - cognitive bias
# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## The Curse of Knowledge in Everyday Life

Several years ago my friend Lauren asked me for my recipe for BBQ seitan. I love food-related conversation, so I wasted no time. "Start by sauteing some chopped onion in oil...", and as quickly as I began, she cut me off. "Hold on," she interjected. "What kind of oil do you use? How much? How high do you turn the heat?"

Dissecting the conversation, what happened was that I implicitly made the absurd assumption that knowledge that is in my head must be in hers (i.e., "Use however much of whatever oil you'd like to at whatever heat you normally saute"). In other words, I fell victim to the [curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge). I'm **not** an expert cook - just ask my wife who always keeps the salt and pepper shaker within arm's reach when I prepare a meal - but I did naively explain  the recipe to Lauren as if she possessed my idiosyncratic definition of "saute".

## The Curse of Knowledge When Teaching R

Scenarios like this are universal, and most of the time, they are harmless. However, they can be frustrating when people have invested time and money to learn R from you. Even if you yourself are relatively to new to R, it is easy to take for granted all that you know and what it's like to be a true beginner. Consider the following questions and confusion that a new R user might have when you ask them to do something as seemingly innocuous as running a line of `read_csv()` code  you've provided:

  - "I just bought a book that says to use `read.csv()`, but you use `read_csv()`. They are so similar they must do exactly the same thing, right? "
  - "Excuse me, but are you saying *tibble*? Do you mean *table*?"
  - "I tried running `read_csv()` but I got an error saying the function couldn't be found. How does *that* make sense?"
  - "I thought you said colons aren't allowed in function names, so  why did you write `readr::read_csv()`?"
  - "The code you shared says `read_csv("raw-data/survey-results.csv")` but I changed the `/` to `\` because that's what the folders look like on my computer and now it doesn't work. WTF, right?!"
  
Not all of your students will tell you when they're stuck, and because you can't read their minds, what are you to do? **Ask them!** Whether it's a one day workshop or a semester long course, giving frequent, brief, assessments will help you identify areas of confusion and guide your lessons. 

You might be thinking that when you have a large group of people, resolving every question that every student has is unrealistic. That may be true, but it is a shame when a student falls behind because an instructor misses an opportunity for a simple clarification. Consider the following (intentionally confusing) passage from Bransford and Johnson (1972):

> The procedure is actually quite simple. First you arrange things into different groups… Of course, one pile may be sufficient depending on how much there is to do. If you have to go somewhere else due to lack of facilities that is the next step, otherwise you are pretty well set. It is important not to overdo any particular endeavor. That is, it is better to do too few things at once than too many. In the short run this may not seem important, but complications from doing too many can easily arise. A mistake can be expensive as well… At first the whole procedure will seem complicated. Soon, however, it will become just another facet of life. It is difficult to foresee any end to the necessity for this task in the immediate future, but then one never can tell. After the procedure is completed one arranges the materials into different groups again. Then they can be put into their appropriate places. Eventually they will be used once more and the whole cycle will have to be repeated. However, that is part of life. (Bransford and Johnson 1972 p. 722)

If you've never seen this passage before, it probably makes little sense to you and its details are unlikely to stick in your mind. But if before you read it I  gave you the passage's title - *Washing Clothes* - it would suddenly become much clearer. There are plenty of "washing clothes" examples in R, and as the instructor, it's your job to construct an environment that helps you identify them.


## Conclusion

Frequent assessments will alert you when you succumb to the curse of knowledge and help you to correct your biases. If you're teaching R - or for that matter, anything - and you're not regularly checking in on what your students know and what their misconceptions are, it's worth asking yourself what your goals are, because maximizing student understanding may not be one of them. 

  


 