---
title: Achieving Reproducibility in IR With R
draft: false
authors: [arie]
event: 'AIR Forum 2018'
event_url: https://www.airweb.org/docs/default-source/documents-for-pages/forum/program-books/air-forum-2018-program-guide.pdf?sfvrsn=8445eb4_2
location: Orlando, Florida
summary: "Demonstrating the value of reproducibility with R and R Markdown to IR institutional researchers."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2018-05-31T10:45:00Z"
#date_end: "2019-09-30T16:30:00Z"
all_day: false
# publishdate: "2019-06-15"

#links:
#- icon: github
#  icon_pack: fab
#  name: materials
#  url: https://github.com/rstudio-education/communicate-rmd-workshop

categories:
  - conference presentation
tags:
  - air2018
  - rmarkdown
# lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: 'center'
  preview_only: no
projects: []
---

Although the concept of reproducibility is typically reserved for the sciences, the presenter will argue that by adopting its principles, IR offices would see immeasurable benefits in efficiency, accuracy, and transparency. Reproducible workflows preserve every decision made about data analyses (e.g., removing a student who withdrew) and allow users to quickly and accurately respond to requests for modifications (e.g., group tables by college instead of major). One barrier to reproducibility, however, is that it requires coding. Using examples from the free R programming language, the presenter will show that not only is R an ideal software for reproducibility, but that many of its modern features are designed to get novices quickly doing powerful things. The primary goals of the presentation are for audience members to leave convinced that they can learn R, and that if they do, they will become better at their jobs.
