---
title: "Creating Data Visualizations Using R: An Introduction for Non-Programmers"
draft: false
authors: [arie]
event: 'AIR Forum 2016'
event_url: https://www.airweb.org/docs/default-source/documents-for-pages/forum/program-books/air-forum-2016-program-guide.pdf?sfvrsn=96fae535_2
location: New Orleans, Louisiana
summary: "The primary goal of the presentation is for audience members to leave feeling empowered to learn to use R to improve the quantity, quality, and reproducibility of their work."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2016-07-01T15:00:00Z"
#date_end: "2019-09-30T15:30:00Z"
all_day: false
# publishdate: "2019-06-15"

#links:
#- icon: github
#  icon_pack: fab
#  name: materials
#  url: https://github.com/rstudio-education/communicate-rmd-workshop

categories:
  - conference presentation
tags:
  - air2016
  - ggplot2
# lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: 'center'
  preview_only: no
projects: []
---

Creating graphs is a central part of the IR workload, but it can be frustrating. If you make graphs using Excel, you might spend hours mindlessly pointing-and-clicking, which then has to be repeated if updates to the graphs are required. The presenter will begin by arguing in favor of two points: First, IR professionals would be better off using R (a free and open-source programming language), and second, even those without any programming experience can learn R well enough to reap its majesty. A demonstration will be given on how to create and modify a scatter plot using ggplot2, an R package for building highly customizable visualizations. The primary goal
of the presentation is for audience members to leave feeling empowered to learn to use R to improve the quantity, quality, and reproducibility of their work
